# 27.异常

什么是异常？Java代码在运行时期发生的问题就是异常。

在Java中，把异常信息封装成了一个类。当出现了问题时，就会创建异常类对象并抛出异常相关的信息（如异常出现的位置、原因等）。



## 常见的异常

1. 编译时异常：必须处理，否则程序不能运行
2. 运行时异常





## 异常的继承体系

java中用Exception类来描述异常，他的父类是Throwable类，是所有错误和异常的超类。

Throwable有两个直接子类，一个是Error类，一个是Exception类

Error类用来表示程序中可能产生的严重错误，解决办法只有修改代码来避免产生错误

Exception用来表示程序中可能产生的异常，并要求对产生的异常进行合理的异常处理。Exception描述编译时的异常，RuntimeException描述运行时的异常



### 异常与错误的区别

**异常**：指程序在编译、运行期间发生了某种异常(XxxException)，我们可以对异常进行具体的处理（抛给调用者或自己捕获）。若不处理异常，程序将会结束运行。

 

**错误**：指程序在运行期间发生了某种错误(XxxError)，Error错误通常没有具体的处理方式，程序将会结束运行。Error错误的发生往往都是系统级别的问题，都是jvm所在系统发生的，并反馈给jvm的。我们无法针对处理，只能修正代码。





## 异常产生流程解析及捕获异常

程序运行时出现异常，jvm会创建一个异常对象，这个对象包含了异常的内容、名称、产生位置。然后将这个对象抛给调用者，如果调用者没有对异常作处理，则继续向上抛异常，如果都没有处理，最终会抛给jvm，jvm不会对异常做处理，只会将异常的信息输出到控制台然后**结束程序**。



使用try语句捕获异常，try语句包含的内容出现异常时会将异常对象捕获，则异常对象不会上抛

使用catch语句对异常进行处理，捕获到异常后代码转到catch语句中执行





## 声明异常throws

格式：修饰符 返回值类型 方法名(参数) throws 异常类名1,异常类名2… {  }



声明：将问题标识出来，报告给调用者。如果方法内通过throw抛出了编译时异常，而没有捕获处理，那么必须通过throws进行声明，让调用者去处理。





## 多重catch

检测到异常后对每种异常信息进行不同的处理

这种异常处理方式要求多个catch中的异常不能相同，并且若catch中的异常之间有子父类异常的关系，子类必须在父类异常处理的前面。



## finally

不管是否发生异常都会执行finally里的代码

~~~java
int str[] = { 12, 564, 6 };
		try {
			System.out.println(str[1]);
			System.out.println("11111");
		} catch (Exception e) {
			// TODO: handle exception
			System.out.println("22222");
		} 
		// 不管是否有异常都要输出
		System.out.println("3333333");//看起来实现了要求，但如果try里面断了，就不行了，如下



	try {
			System.out.println(str[1]);
			System.out.println("11111");
			return;		//这里一个return导致333输出不了，这时finally才能真正保证333一定输出
		} catch (Exception e) {
			// TODO: handle exception
			System.out.println("22222");
		} finally {
			// 不管是否有异常都要输出
			System.out.println("3333333");

		}
~~~

finally一般用来关闭一些资源



## try finally组合

对代码进行异常检测，检测到异常后因为没有catch，所以一样会被默认jvm抛出。异常是没有捕获处理的。但是功能所开启资源需要进行关闭，所有finally。只为关闭资源。

没有对异常进行处理，发生异常后，执行完finally的代码，jvm打印异常信息，程序结束





## throw

抛出一个指定的异常对象

注意：throw是抛出一个自己创建的异常对象，在方法内；throws是声明异常，在方法声明中。

工具类：

~~~java
class ArrayTools{
	//通过给定的数组，返回给定的索引对应的元素值。
	public static int getElement(int[] arr,int index)	{
		/*
		若程序出了异常，JVM它会打包异常对象并抛出。但是它所提供的信息不够给力。想要更清晰，需要自己抛出异常信息。
下面判断条件如果满足，当执行完throw抛出异常对象后，方法已经无法继续运算。这时就会结束当前方法的执行，并将异常告知给调用者。这时就需要通过异常来解决。
		*/
		if(arr==null){
			throw new NullPointerException("arr指向的数组不存在");
		}
		if(index<0 || index>=arr.length){
			throw new ArrayIndexOutOfBoundsException("错误的角标，"+index+"索引在数组中不存在");
		}
		int element = arr[index];
		return element;
	}
}
~~~

测试类：

~~~java
class ExceptionDemo3 {
	public static void main(String[] args) {
		int[] arr = {34,12,67}; //创建数组
		int num = ArrayTools.getElement(null,2);// 调用方法，获取数组中指定索引处元素
//int num = ArrayTools.getElement(arr,5);// 调用方法，获取数组中指定索引处元素
		System.out.println("num="+num);//打印获取到的元素值
	}
}
~~~



## 运行时异常（RuntimeException）及特点

特点：方法中抛出运行时异常，方法定义中无需throws声明，调用者也不用处理

发生运行时异常，需要修改代码才能处理

运行时异常可以不做处理，但也可以捕获处理





## 异常在重写中的注意事项

1. 子类不能抛出比父类更大范围的异常（需要注意运行时异常因为可以声明也可以不声明，所以子类抛出的运行时异常比父类范围大是不会报错的），或者不抛出
2. 父类方法没有声明异常，则子类的异常只能捕获（不改变父类方法的情况下）



问题：接口中没有声明异常，而实现的子类覆盖方法时发生了异常，怎么办？

答：无法进行throws声明，只能catch的捕获。万一问题处理不了呢？catch中继续throw抛出，但是只能将异常转换成RuntimeException子类抛出。





## 异常中的常用方法

~~~java
try {

			int i = 10;
			int i2 = 0;
			System.out.println(i / i2);
			int[] a = { 123, 345, 54 };
			System.out.println(a[1]);
		} catch (Exception e) {
//			e.printStackTrace();// 输出的异常标志错误流（异常名称，异常内容，异常位置）推荐
			// System.out.println(e);//输出的是异常对象(异常名称，异常内容)
//			System.out.println(e.getMessage());//输出的是异常内容
//			System.out.println(e.toString());// 输出的是异常对象(异常名称，异常内容)

		}
~~~

其实用printStackTrace就够了





## 自定义异常

自定义异常，只用一个类继承Exception类就有了异常的所有特性

**格式：**

~~~java
class 异常名 extends Exception{ //或继承RuntimeException

class public 异常名(){

}

class public 异常名(String s){ 

super(s); 

}

}
~~~

例子：

自定义异常：

~~~java
public class AgeOutException extends Exception {
	// 构造器
	public AgeOutException() {

	}

	public AgeOutException(String message) {
		super(message);
	}

}
~~~

Student类：

~~~java
public class Student {
	private String name;
	private String password;
	private int age;

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public int getAge() {
		return age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public Student(String name, String password, int age) throws AgeOutException {
		super();
		if (age < 0 || age > 150) {
			throw new AgeOutException("年龄不合法");
		}
		System.out.println("1111111"); 
		this.name = name;
		this.password = password;
		this.age = age;
	}

}
~~~

测试：

~~~java
public static void main(String[] args) throws AgeOutException{
			Student stu =  new Student("张三", "123", 180);//提示年龄不合法
	}
~~~









## 练习：

定义Person类，包含name与age两个成员变量。

在Person类的有参数构造方法中，进行年龄范围的判断，若年龄为负数或大于200岁，则抛出NoAgeException异常，异常提示信息“年龄数值非法”。

要求：在测试类中，调用有参数构造方法，完成Person对象创建，并进行异常的处理。

 

要求：添加一个password属性，必须是5到15位的数字+字母组成，如果不是就自定义处理





~~~java
public class Text1 {
	public static void main(String[] args) throws AgeException, PasswordException {
		System.out.println(new Person("张三", 200,"1234145").getPassword());
	}

}

class Person{
	private String name;
	private int age;
	private String password;
	/**
	 * @param name
	 * @param age
	 * @param password
	 * @throws AgeException 
	 * @throws PasswordException 
	 */
	public Person(String name, int age, String password) throws AgeException, PasswordException {
		if(age<0 || age>200) {
			throw new  AgeException("年龄超出范围！");
		}
		String reg="^[0-9a-zA-Z_]{5,15}$";
		if(!password.matches(reg)) {
			System.out.println("密码格式错误！自动将密码改为：12345");
			password="12345";
		}
		this.name = name;
		this.age = age;
		this.password = password;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public int getAge() {
		return age;
	}
	public void setAge(int age) {
		this.age = age;
	}
	
}

class AgeException extends Exception {
	/**
	 * 
	 */
	public AgeException() {
		// TODO Auto-generated constructor stub
	}
	
	public AgeException(String s) {
		// TODO Auto-generated constructor stub
		super(s);
	}
}

class PasswordException extends Exception{
	/**
	 * 
	 */
	public PasswordException() {
		// TODO Auto-generated constructor stub
	}
	
	public PasswordException(String s) {
		// TODO Auto-generated constructor stub
		super(s);
	}
}
~~~

